from backend.ms_arc.state.retrieval_state import (
    RetrievalState
)

from backend.ms_arc.state.retrieval_signals import (
    AgreementMetrics
)


def compute_agreement(
    state: RetrievalState,
) -> RetrievalState:

    """
    Computes weighted Dense/BM25 retrieval agreement.

    Agreement is based on the actual candidate sets
    generated by the current hybrid retrieval.

    Formula:

        weighted intersection
        ---------------------
        weighted union

    where each document contributes its normalized
    dense and sparse retrieval scores.
    """

    # ======================================================
    # DENSE LOOKUP
    # ======================================================

    dense = {

        doc.doc_id: doc

        for doc in state.dense_results

    }

    # ======================================================
    # SPARSE LOOKUP
    # ======================================================

    sparse = {

        doc.doc_id: doc

        for doc in state.sparse_results

    }

    dense_ids = set(
        dense.keys()
    )

    sparse_ids = set(
        sparse.keys()
    )

    intersection = (
        dense_ids
        &
        sparse_ids
    )

    union = (
        dense_ids
        |
        sparse_ids
    )

    # ======================================================
    # WEIGHTED INTERSECTION
    # ======================================================

    numerator = 0.0

    for doc_id in intersection:

        numerator += (

            dense[
                doc_id
            ].dense_score

            +

            sparse[
                doc_id
            ].sparse_score

        )

    # ======================================================
    # WEIGHTED UNION
    # ======================================================

    denominator = 0.0

    for doc_id in union:

        weight = 0.0

        if doc_id in dense:

            weight += (
                dense[
                    doc_id
                ].dense_score
            )

        if doc_id in sparse:

            weight += (
                sparse[
                    doc_id
                ].sparse_score
            )

        denominator += weight

    # ======================================================
    # AGREEMENT
    # ======================================================

    if denominator <= 1e-12:

        agreement = 0.0

    else:

        agreement = (
            numerator
            /
            denominator
        )

    agreement = max(
        0.0,
        min(
            1.0,
            agreement
        )
    )

    # ======================================================
    # STORE METRICS
    # ======================================================

    state.signals.agreement = (
        AgreementMetrics(

            score=agreement,

            intersection=len(
                intersection
            ),

            union=len(
                union
            ),

        )
    )

    # ======================================================
    # DEBUG
    # ======================================================

    state.debug[
        "agreement_intersection"
    ] = len(
        intersection
    )

    state.debug[
        "agreement_union"
    ] = len(
        union
    )

    state.debug[
        "agreement_score"
    ] = agreement

    print(
        "[Optimization #6] "
        f"Agreement: {agreement:.4f}"
    )

    print(
        "[Optimization #6] "
        f"Intersection: "
        f"{len(intersection)}"
    )

    print(
        "[Optimization #6] "
        f"Union: "
        f"{len(union)}"
    )

    return state